// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48SGHOBsVrn_GlGZF9eF-BSzaH5BpnZE',
    appId: '1:1091504397205:web:990772456f5442a530349c',
    messagingSenderId: '1091504397205',
    projectId: 'tripbudgeter-4811f',
    authDomain: 'tripbudgeter-4811f.firebaseapp.com',
    storageBucket: 'tripbudgeter-4811f.appspot.com',
    measurementId: 'G-J2D031FNHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVTQbCVmsNPUytRSkZ8lRwkcVHvS2cnjE',
    appId: '1:1091504397205:android:93dab531a4a66aa430349c',
    messagingSenderId: '1091504397205',
    projectId: 'tripbudgeter-4811f',
    storageBucket: 'tripbudgeter-4811f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy-HS7_WGdmxRajFSl8BHcAYw-j4zdCL8',
    appId: '1:1091504397205:ios:42353a3884acc52330349c',
    messagingSenderId: '1091504397205',
    projectId: 'tripbudgeter-4811f',
    storageBucket: 'tripbudgeter-4811f.appspot.com',
    iosBundleId: 'com.example.tripBudgeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy-HS7_WGdmxRajFSl8BHcAYw-j4zdCL8',
    appId: '1:1091504397205:ios:42353a3884acc52330349c',
    messagingSenderId: '1091504397205',
    projectId: 'tripbudgeter-4811f',
    storageBucket: 'tripbudgeter-4811f.appspot.com',
    iosBundleId: 'com.example.tripBudgeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB48SGHOBsVrn_GlGZF9eF-BSzaH5BpnZE',
    appId: '1:1091504397205:web:fdd9daeefc59567b30349c',
    messagingSenderId: '1091504397205',
    projectId: 'tripbudgeter-4811f',
    authDomain: 'tripbudgeter-4811f.firebaseapp.com',
    storageBucket: 'tripbudgeter-4811f.appspot.com',
    measurementId: 'G-1FGG6MWWSD',
  );
}
